### PR TITLE
No pagination when job count is less than 20

### PR DESCRIPTION
**Pull request by clrke**

### CODE REVIEW

**Comment by marksteve** [comment]
@arkeidolon Try using the `classSet` addon function:

`var className = React.addons.classSet({
  'pagination-hidden': noPagination
});`

Also, seems like the compiled version of `main.js` was deleted?

**Comment by clrke** [comment]
@marksteve compiled version? You mean the 3rd file here?
image

**Comment by marksteve** [comment]
@arkeidolon yep. Or wait, maybe that's just because of the paths in the compiled version. Yeah don't mind that.

**Comment by clrke** [comment]
@marksteve commited another one e548020d2176ac5174ac47e7f4ffdbb0f228dbf4

**Comment by marksteve** [comment]
:+1:

**Pull request merged**
